# Basic
title: Ke Xiang
subtitle: Code Create Life
description: Do more, Know more, Be more!

url: "http://fi-null.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Resume, description: resume, url: 'https://fi-null.github.io/resumeWeb/'}
    #- {title: About, description: about, url: '/about'}

# Pagination
plugins: [jekyll-paginate]
paginate: 2
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: fi-null
    github: fi-null
    twitter: fi-null
    gplus: 107108267983477358170
    mail: xiangke123401@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
